export const AUDIT_ACTIONS = [
  'system.genesis',
  'auth.password.success',
  'auth.login.failure',
  'auth.login.success',
  'auth.account.locked',
  'auth.account.unlocked',
  'auth.mfa.webauthn.success',
  'auth.mfa.webauthn.failure',
  'auth.mfa.email.sent',
  'auth.mfa.email.success',
  'auth.mfa.email.failure',
  'auth.mfa.email.exhausted',
  'auth.stepup.granted',
  'auth.stepup.failed',
  'auth.logout',
  'auth.password.changed',
  'auth.password.reset',
  'webauthn.credential.registered',
  'webauthn.credential.revoked',
  'webauthn.counter.anomaly',
  'user.created',
  'user.updated',
  'user.role.changed',
  'user.disabled',
  'user.enabled',
  'authz.denied',
  'security.origin.rejected',
  'security.rate_limited',
  'product.created',
  'product.updated',
  'product.controlled.changed',
  'inventory.receipt',
  'inventory.adjustment',
  'sale.created',
  'sale.voided',
  'customer.created',
  'customer.viewed',
  'customer.updated',
  'customer.consent.withdrawn',
  'prescription.created',
  'prescription.viewed',
  'prescription.cancelled',
  'prescription.dispensed',
  'audit.viewed',
  'audit.exported',
  'audit.verified',
  'report.viewed',
  'report.exported',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditResult = 'success' | 'failure' | 'denied';
